### ISSUE TITLE
npm run  build报错

### ISSUE THREAD

**Issue by yongyangwu** [hwjfqr/component-lib-demo#1]
![image](https://user-images.githubusercontent.com/26920403/147733149-f35ff9fe-1eba-423f-b5d8-2f9cd4515c31.png)
### 老板这个打包报错啊

**Comment by hwjfqr** [comment]
为防止打包时可能出现的类型报错，建议安装 @types/react、@types/react-dom 等相关依赖： npm i -D @types/react @types/react-dom​
